/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_win32_mediafoundation_IMFAttributes */

#ifndef _Included_com_khopan_win32_mediafoundation_IMFAttributes
#define _Included_com_khopan_win32_mediafoundation_IMFAttributes
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_win32_mediafoundation_IMFAttributes
	 * Method:    SetGUID
	 * Signature: (Lcom/khopan/win32/mediafoundation/GUID;Lcom/khopan/win32/mediafoundation/GUID;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_khopan_win32_mediafoundation_IMFAttributes_SetGUID
	(JNIEnv*, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
