/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_win32_BareMetal */

#ifndef _Included_com_khopan_win32_BareMetal
#define _Included_com_khopan_win32_BareMetal
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_win32_BareMetal
	 * Method:    GetMemoryAddress
	 * Signature: (Ljava/lang/Object;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_khopan_win32_BareMetal_GetMemoryAddress
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     com_khopan_win32_BareMetal
	 * Method:    UpdateObject
	 * Signature: (JLjava/lang/Object;)V
	 */
	JNIEXPORT void JNICALL Java_com_khopan_win32_BareMetal_UpdateObject
	(JNIEnv*, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
