/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_win32_mediafoundation_IMFActivate */

#ifndef _Included_com_khopan_win32_mediafoundation_IMFActivate
#define _Included_com_khopan_win32_mediafoundation_IMFActivate
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_win32_mediafoundation_IMFActivate
	 * Method:    GetAllocatedString
	 * Signature: (Lcom/khopan/win32/mediafoundation/GUID;Lcom/khopan/win32/utils/MutableString;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_khopan_win32_mediafoundation_IMFActivate_GetAllocatedString
	(JNIEnv*, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
